services:
  apache:
    image: httpd:2.4
    container_name: apache_jau_jau
    ports:
      - "8080:80"
    volumes:
      - ./www:/usr/local/apache2/htdocs:ro
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    restart: unless-stopped